[service]
name = "agetty-tty1"
exec = ["/sbin/agetty", "--noclear", "tty1", "linux"]
type = "simple"

[restart]
policy = "permanent"
delay = "1s"
max-restarts = 10
max-restart-window = "30s"

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGHUP"
stop-timeout = "3s"
