[service]
name = "fstab-mount"
supervisor = "early-boot"
exec = ["/bin/mount", "-a"]
type = "oneshot"

[restart]
policy = "temporary"

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "3s"
