[service]
name = "hostname"
supervisor = "early-boot"
exec = ["/bin/hostname", "-F", "/etc/hostname"]
type = "oneshot"

[restart]
policy = "temporary"

[dependencies]
after = ["fstab-mount"]

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "3s"
