[service]
name = "machine-id"
supervisor = "early-boot"
exec = ["/sbin/dynamod-init", "--write-machine-id"]
type = "oneshot"

[restart]
policy = "temporary"

[dependencies]
requires = ["remount-root-rw"]

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "3s"
