[service]
name = "mdev-coldplug"
supervisor = "early-boot"
exec = ["/sbin/mdev", "-s"]
type = "oneshot"

[restart]
policy = "temporary"

[dependencies]
requires = ["modules-load"]

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "5s"
