[service]
name = "network"
exec = ["/bin/sh", "-c", "ip link set lo up && ip addr add 127.0.0.1/8 dev lo"]
type = "oneshot"

[restart]
policy = "temporary"

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "5s"
