[service]
name = "remount-root-rw"
supervisor = "early-boot"
exec = ["/bin/mount", "-o", "remount,rw", "/"]
type = "oneshot"

[restart]
policy = "temporary"

[dependencies]
requires = ["fsck"]

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "3s"
