[service]
name = "dynamod-logd"
supervisor = "early-boot"
exec = ["/usr/lib/dynamod/dynamod-logd"]
type = "simple"

[restart]
policy = "permanent"
delay = "1s"

[dependencies]
after = ["bootmisc"]

[readiness]
type = "none"

[shutdown]
stop-signal = "SIGTERM"
stop-timeout = "5s"
